# Dockerfile

# ======= 1. BASE 스테이지 =======
FROM node:22-alpine AS base
# 작업 위치 설정 - 해당 컨테이너 위치 
WORKDIR /app

# pnpm 설치 
RUN npm install -g pnpm

# package.json, pnpm-lock.yaml 등 의존성 관련 파일만 복사
COPY package.json pnpm-lock.yaml ./


# ======= 1. dev용 스테이지 ========
FROM base AS dev_runner
# 의존성 설치 - dev 용
RUN pnpm install

# ======= 2. 빌드 스테이지 ========
FROM dev_runner AS builder

# 나머지 소스 코드 전체 복사 
COPY . .

# Schema 
RUN pnpm prisma generate 

# 애플리케이션 빌드
RUN pnpm run build

# ======= 2. 의존성 증류 스테이지 ========
FROM base AS prod_modules_setter

# 의존성 중 production용만 받아오기
RUN pnpm install --prod

# ======= 3. prod 실행 스테이지 ========
FROM node:22-alpine AS runner

# 작업 디렉토리 설정 
WORKDIR /app

# 빌드 스테이지의 운영에 필요한 파일들만 복사 
# 1. 빌드 결과물 
COPY --from=builder /app/dist ./dist

# 2. 운영용 의존성
COPY --from=prod_modules_setter /app/node_modules ./node_modules

# 3. package.json 파일
COPY --from=prod_modules_setter /app/package.json ./package.json

# 4. Prisma Client 엔진 및 코드 복사 
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

# 애플리케이션이 사용할 포트 노출 
EXPOSE 3000

# 컨테이너 시작 시 명령어
CMD ["node", "dist/main"]
