apiVersion: v1
kind: ConfigMap 
metadata:
  name: protostar-nest-config
  namespace: service
  labels:
    app: protostar
    tier: backend
data:
  REDIS_HOST: "192.168.0.37"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MINIO_ENDPOINT: "http://192.168.0.41:9000"
  MINIO_BUCKET_NAME: "protostar-knowledge"
  MINIO_REGION: "us-east-1"
  