apiVersion: apps/v1
kind: Deployment
metadata:
  name: protostar-nest
  namespace: service
  labels:
    app: protostar
    tier: backend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protostar
      tier: backend
  template:
    metadata:
      labels:
        app: protostar
        tier: backend
        env: dev
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: A5
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: protostar-nest
          image: ghcr.io/paul2021-r/project-protostar-nest:61
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
               name: protostar-nest-config
            - secretRef:
               name: protostar-nest-secret
          resources: 
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"